server:
  port: 8080
spring:
  h2:
    console:
      path: /h2-console
      enabled: on
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  sql:
    init:
      mode: always
      data-locations: test_data.sql
      schema-locations: schema.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

