server:
  port: 8030

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  sql:
    init:
      mode: always
      data-locations: test_data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

